# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: trion/ng-cli

pipelines:
    branches:
        develop:
            - step:
                  caches:
                      - node
                  name: build the angular
                  script:
                      - npm install
                      - ng build
                      - ng b -op dist-demo --bh /demo/
                  artifacts:
                      - dist/**
                      - dist-demo/**
            - step:
                  name: Login and build the docker image
                  script: # Modify the commands below to build your repository.
                      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
                      - docker build -t givt/givtdashboarddebug:latest .
                      - docker push givt/givtdashboarddebug:latest
                  services:
                      - docker
        master:
            - step:
                caches:
                    - node
                name: build the angular
                script:
                    - npm install
                    - ng build --prod
                    - ng build -op dist-demo --bh /demo/
                artifacts:
                    - dist/**
                    - dist-demo/**
            - step:
                name: Login and build the docker image
                script: # Modify the commands below to build your repository.
                    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
                    - docker build -t givt/givtdashboard:master .
                    - docker push givt/givtdashboard:master
                services:
                    - docker

